import {StyleSheet, Dimensions} from "react-native";

const windowWidth = Dimensions.get("window").width;

export const styles = StyleSheet.create({
  eventHeader: {
    fontWeight: "bold",
    fontSize: 20,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 5,
    paddingTop: 5,
    paddingLeft: 35,
    paddingRight: 35,
    borderTopWidth: 2,
  },
  joinSubHeader: {
    fontWeight: "bold",
    fontSize: 18,
    alignSelf: "flex-start",
    marginTop: 10,
    paddingLeft: 15,
  },

  container: {
    flex: 1,
    marginVertical: 5,
  },
  item: {
    backgroundColor: "rgba(100,50,190, 0.08)",
    padding: 10,
    marginTop: 10,
    marginHorizontal: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    // borderWidth: 2,
    borderLeftWidth: 2,
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: "#333",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    textTransform: "capitalize",
    width: windowWidth / 3,
    textAlign: "left",
    paddingBottom: 5,
  },
  location: {
    textAlign: "left",
    fontSize: 18,
    textTransform: "capitalize",
    width: windowWidth / 3,
  },
  date: {
    textAlign: "right",
    fontSize: 18,
    textTransform: "capitalize",
    width: windowWidth / 2,
  },
  time: {textAlign: "right", fontSize: 18, width: windowWidth / 2},
  user: {textAlign: "right", fontSize: 18, width: windowWidth / 3},
  description: {
    fontSize: 16,
    width: windowWidth,
    marginTop: 5,
    marginLeft: 15,
  },
  category: {
    textAlign: "left",
    fontSize: 18,
    textTransform: "capitalize",
    width: windowWidth / 3,
  },

  requestsButton: {
    // borderLeftWidth: 2,
    // borderBottomWidth: 2,
    // borderRightWidth: 2,
    borderWidth: 2,
    borderColor: "#333",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    // backgroundColor: "rgba(120,50,240, 0.25)",
    padding: 5,
    width: windowWidth / 1.085,
    alignSelf: "center",
  },
  deleteButton: {
    // borderLeftWidth: 2,
    // borderBottomWidth: 2,
    // borderRightWidth: 2,
    borderWidth: 2,
    borderColor: "#333",
    borderRadius: 8,
    // backgroundColor: "rgba(120,50,240, 0.25)",
    padding: 5,
    marginTop: 5,
    width: windowWidth / 1.085,
    alignSelf: "center",
  },
  buttonTitle: {
    textAlign: "center",
    fontWeight: "bold",
  },
});
