import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    margin: 10,
  },
  view: {
    backgroundColor: "#FFF",
    flex: 1,
    padding: 10,
    borderRadius: 10,
    marginHorizontal: 25,
    marginTop: 10,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: "#DADBDF",
  },
  myEventView: {
    backgroundColor: "#FFF",
    padding: 10,
    paddingBottom: 50,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginHorizontal: 25,
    marginTop: 10,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: "#DADBDF",
  },
  capitalizedText: {
    fontSize: 18,
    margin: 5,
    textTransform: "capitalize",
  },
  text: {
    fontSize: 18,
    margin: 5,
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    alignSelf: "center",
    padding: 10,
    textTransform: "capitalize",
  },
  PressableText: {
    padding: 4,
    fontSize: 18,
    textAlign: "center",
    color: "whitesmoke",
  },
  pressableContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 25,
  },
  pressable: {
    marginBottom: 10,
    // flex: 1,
    marginHorizontal: 2,
    borderWidth: 1,
    borderColor: "#323B76",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: "#323B76",
    padding: 8,
    alignSelf: "center",
  },
  hostView: {
    backgroundColor: "#FFF",
    flex: 3,
    padding: 10,
    borderRadius: 10,
    marginHorizontal: 25,
    marginTop: 10,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: "#DADBDF",
  },
  eventView: {
    backgroundColor: "#FFF",
    flex: 5,
    padding: 10,
    borderRadius: 10,
    marginHorizontal: 25,
    marginTop: 10,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: "#DADBDF",
  },
});
